Mirror plugins during build
getporter/terraform-mixin pull request #93
Opened 2022-08-31 18:57 UTC by tamirkamara

Fixes #90.

When we build the bundle we can and should mirror the plugins terraform would use in runtime so that the bundle will be more self sufficient and won't need to access Terraform/Hashicorp endpoints to download things.

2022-08-31 19:14 UTC, tamirkamara commented
@carolynvs I've tested this in a basic way but if easy enough I would have liked to take it into our harden environment and run it there. Is it possible to package the mixin as a file and then have `porter mixin install` it via a file path and not a URL?

2022-09-02 14:44 UTC, carolynvs commented
@tamirkamara You can install the mixin from source with `mage build install`. Afterwards you can copy `~/.porter/mixins/terraform` to another machine (has to be the same OS/ARCH).

2022-09-07 17:58 UTC, tamirkamara commented
@carolynvs looks like it also works in our constraint environment. Can you please reivew?

2022-09-08 21:52 UTC, carolynvs requested changes
I tried this out with a test bundle and it seems there there is more configuration required to make this work. It didn't work for me and still downloaded the providers.

Is there more that needs to be done to make this work? Maybe some configuration file changes? If we are going to unconditionally mirror the providers, then the mixins should configure the bundle to automatically take advantage of those files.

2022-09-09 12:03 UTC, tamirkamara commented
> I tried this out with a test bundle and it seems there there is more configuration required to make this work. It didn't work for me and still downloaded the providers.

@carolynvs can you explain how and where you saw it downloaded the providers?
I have run this in an environment where at runtime porter can't access terraform/hashicorp domains and everything worked just fine. The providers were downloaded at build time and saved in the image.

2022-09-09 14:12 UTC, carolynvs commented
I was getting confused by this output:

```
Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Installing hashicorp/azurerm v2.72.0...
- Installed hashicorp/azurerm v2.72.0 (unauthenticated)
```

It was taking a long time and I assumed it was installing the providers again. I just tried again with my network unplugged and confirmed that it is in fact using the mirrored providers. 👍

2022-09-09 14:13 UTC, carolynvs approved these changes
Thank you for making this feature work _much better_ in airgapped scenarios!

2022-09-09 14:13 UTC, merged